name: Test building for production
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout
      - uses: actions/checkout@v2

      # Step 2: Add SSH credentials to your GitHub CI/CD instance
      - name: Add SSH Credentials
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} # required, this will be used when transferring files to your deploy targets
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }} # required, should match up with your deploy targets (see below)

      # Step 3: Deploy!
      - name: Deploy to Staging
        uses: JorgenVatle/docker-compose-deploy@v1.0
        with:
          deploy_targets: "tuspl22-momentum.srv.mwn.de" # required, comma separated list of servers to deploy to.

          ssh_user: "github" # optional, user to connect to deploy targets with. Defaults to 'root'
          compose_file: "docker-compose.yml" # optional, path/filename of your docker-compose file. Defaults to 'docker-compose.yml'
          # validate_container: 'app' # optional, validate that the given container name is running. Otherwise, throw an error. Defaults to 'app'
